POST http://127.0.0.1:8000/api/token/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1NTg1NDk1LCJpYXQiOjE3MzU1ODUxOTUsImp0aSI6IjUzYmMyNTIxYWQwZjQyNWE4YTdmODE5NTNmM2E3MGRiIiwidXNlcl9pZCI6Mn0.JHtT7cN-KMtPCxj-FJ0x47qzTtXEb8L0G4n_lcsr-jk

{
    "username": "admin12",
    "password": "12345"
}

###

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "username": "tisha_grover",
    "email": "tishagrover4@gmail.com",
    "first_name": "Tisha",
    "last_name": "Grover",
    "password": "password123"
}

###

GET http://127.0.0.1:8000/api/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/api/cart/ HTTP/1.1

###

POST /api/cart/
Host: 127.0.0.1:8000
Authorization: Bearer <your_token>
Content-Type: application/json

{
  "product_id": 1
}

