# Generated by Django 4.2.17 on 2025-01-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_image_cart_added_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
