# Generated by Django 4.2.17 on 2025-01-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_added_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="added_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="1.webp", upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
