# Generated by Django 4.2.17 on 2025-01-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_added_at_remove_product_updated_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
